USE mamezou;

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ITEMS;


-- 商品テーブルの作成
CREATE TABLE ITEMS (
    ID              INTEGER     NOT NULL AUTO_INCREMENT,
    NAME            VARCHAR(64) NOT NULL COMMENT '商品名',
    AREA            VARCHAR(64) NOT NULL COMMENT '原産地域',
    ORIGINAL_HOME   VARCHAR(64) NOT NULL COMMENT '原産地',
    PRICE           INTEGER     NOT NULL COMMENT '価格',
    CONSTRAINT PK_ITEMS_ID PRIMARY KEY(ID)
) COMMENT='商品';

-- AUTO_INCREMENT の開始値を設定
ALTER TABLE ITEMS AUTO_INCREMENT = 1001;


-- 注文テーブルの作成
CREATE TABLE ORDERS (
    ID          INTEGER     NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(64) NOT NULL COMMENT '氏名',
    ADDRESS     VARCHAR(128) NOT NULL COMMENT '住所',
    TEL_NUMBER  VARCHAR(64) NOT NULL COMMENT '電話',
    ITEM_ID     INTEGER     NOT NULL COMMENT '注文商品ID',
    CONSTRAINT PK_ORDERS_ID PRIMARY KEY(ID),
    CONSTRAINT FK_ORDERS_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
) COMMENT='注文';

-- AUTO_INCREMENT の開始値を設定
ALTER TABLE ORDERS AUTO_INCREMENT = 2001;

-- 初期データの挿入
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('キリマンジャロ', 'アフリカ', 'タンザニア', 500);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('モカ', 'アフリカ', 'エチオピア', 400);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('モカ', '中東', 'イエメン', 650);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('マンデリン','アジア', 'スマトラ島', 500);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('ジャワコーヒー', 'アジア', 'ジャワ島', 450);

INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('ベトナム', 'アジア', 'ベトナム', 600);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('コナ', 'ハワイ', 'ハワイ島', 850);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('ブルーマウンテン', 'カリブ', 'ジャマイカ', 1700);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('クリスタルマウンテン', 'カリブ', 'キューバ', 700);
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('ハイチコーヒー', 'カリブ', 'ハイチ', 450);

-- INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('グァテマラ', '中央アメリカ', 'グァテマラ', 600);
-- INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('コスタリカ', '中央アメリカ', 'コスタリカ', 550);
-- INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('ブラジル', '南アメリカ', 'ブラジル', 500);
-- INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('エメラルドマウンテン', '南アメリカ', 'コロンビア', 800);

COMMIT;