-- 商品テーブルの作成(外部キー制約より)
CREATE TABLE IF NOT EXISTS ITEMS (
    ID              INTEGER     NOT NULL AUTO_INCREMENT,
    NAME            VARCHAR(64) NOT NULL COMMENT '商品名',
    AREA            VARCHAR(64) NOT NULL COMMENT '原産地域',
    ORIGINAL_HOME   VARCHAR(64) NOT NULL COMMENT '原産地',
    PRICE           INTEGER     NOT NULL COMMENT '価格',
    CONSTRAINT PK_ITEMS_ID PRIMARY KEY(ID)
) COMMENT='商品';

-- 全件削除
SET foreign_key_checks = 0;	-- 外部キー制約を無効にする
TRUNCATE TABLE ITEMS;
SET foreign_key_checks = 1;	-- 外部キー制約を有効にする

-- AUTO_INCREMENT の開始値を設定
ALTER TABLE ITEMS AUTO_INCREMENT = 1001;

-- 注文テーブルの作成
CREATE TABLE IF NOT EXISTS ORDERS (
    ID          INTEGER     NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(64) NOT NULL COMMENT '氏名',
    ADDRESS     VARCHAR(128) NOT NULL COMMENT '住所',
    TEL_NUMBER  VARCHAR(64) NOT NULL COMMENT '電話',
    ITEM_ID     INTEGER     NOT NULL COMMENT '注文商品ID',
    CONSTRAINT PK_ORDERS_ID PRIMARY KEY(ID),
    CONSTRAINT FK_ORDERS_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
) COMMENT='注文';

-- 全件削除
SET foreign_key_checks = 0;	-- 外部キー制約を無効にする
TRUNCATE TABLE ORDERS;
SET foreign_key_checks = 1;	-- 外部キー制約を有効にする

-- AUTO_INCREMENT の開始値を設定
ALTER TABLE ORDERS AUTO_INCREMENT = 2001;

-- 初期データの挿入
INSERT INTO ITEMS (NAME, AREA, ORIGINAL_HOME, PRICE) VALUES ('商品1', '原産地1', '原産地域1', 100);


COMMIT;